import admin from '@/config/firebase-admin'; // Import the default initialized admin instance
// We also need the admin namespace for types if not already imported, but firebase-admin is already imported for that.
import { Timestamp, FieldValue, DocumentData } from 'firebase-admin/firestore'; // Import types
import { getDatabase } from 'firebase-admin/database'; // Still need this for getDatabase

// Assuming these types are compatible or can be redefined/imported as needed.
// For simplicity, I'm defining a basic structure here.
// Ideally, share types from a common location if they are identical to firestoreService.ts types.
interface OrderItemDetailAdmin {
  id: string;
  name: string;
  price: number;
  quantity: number;
  image?: string;
  aguaDelDia?: string;
  entrada?: string;
  platoFuerte?: string;
  sopa?: string;
}

interface OrderItemAdmin {
  details: OrderItemDetailAdmin;
}

interface DeliveryInfoAdmin {
  nombre: string;
  direccion: string;
  codigoPostal: string;
  numeroCelular: string;
  direccionesEntrega: string;
  location?: { latitude: number | null; longitude: number | null } | null;
}

interface DeliveryDateTimeAdmin {
  fecha: Date | null; // Expect JS Date from client payload via API
  hora: string;
}

interface CreateAdminOrderData {
  items: OrderItemAdmin[];
  deliveryInfo: DeliveryInfoAdmin;
  deliveryDateTime: DeliveryDateTimeAdmin;
  paymentMethod: string;
  orderId: string; // Pre-generated by orderService
  userId: string;
  restaurantId: string;
  totalAmount: number;
  paymentDetails?: Record<string, any>;
  initialStatus?: Record<string, any> | string; // Can be string like "active" or an object
}

// Removed import of initializeRealTimeOrder from './realtimeDbService'
// as this service will now handle it directly using Admin SDK.

// Get Firestore instance from the default initialized admin.
const adminDb = admin.firestore();
// RTDB instance will be fetched inside functions after config checks.

// Define UserProfile type for admin service, can be shared or re-defined
// This should match the structure of your user documents in Firestore
export interface UserProfileAdmin {
  id: string;
  email?: string; // Assuming email is present
  name?: string;
  role?: string; // Crucially, we need the role
  hashedPassword?: string;
  image?: string; // This might be the same as photoURL, consider consolidating
  createdAt?: Timestamp | Date; // Can be Date before Firestore conversion
  lastLoginAt?: Timestamp | Date; // Can be Date before Firestore conversion
  latestOrderId?: string;
  provider?: string; // e.g., 'firebase', 'credentials'
  photoURL?: string | null; // From Firebase token
}

// This function now orchestrates Firestore write and RTDB initialization
export const createOrderAndInitializeRTDBAsAdmin = async (orderData: CreateAdminOrderData): Promise<string> => {
  console.log('[Admin Service] Attempting to create order and initialize RTDB with data:', JSON.stringify(orderData, null, 2));
  // Ensure the default admin app has databaseURL for RTDB operations
  // The main admin instance is already initialized by config/firebase-admin.ts
  // We rely on that initialization to have set the databaseURL.
  // admin.app() would give the default app, admin.app().options.databaseURL
  if (!admin.app().options.databaseURL) {
    console.error('[Admin Service] Default Firebase Admin App is missing databaseURL. RTDB operations will fail.');
    throw new Error("Firebase Admin App not properly initialized with databaseURL.");
  }
  const adminRtdb = admin.database(); // Get RTDB instance from the default app
  const orderRef = adminDb.collection("orders").doc(orderData.orderId);
  const userRef = adminDb.collection("users").doc(orderData.userId);

  let finalDeliveryDateTime: any = { ...orderData.deliveryDateTime };
  if (orderData.deliveryDateTime && orderData.deliveryDateTime.fecha instanceof Date) {
    finalDeliveryDateTime.fecha = Timestamp.fromDate(orderData.deliveryDateTime.fecha);
  }
  // If fecha is already a Timestamp (e.g., from server-side processing before this point), or null, it's fine.

  try {
    // Optional: Check for existing active order using Admin SDK if strict "one active order" rule is needed
    // This check is not strictly necessary for permission bypass but can be good for business logic.
    const activeOrderQuery = adminDb.collection("orders")
      .where("userId", "==", orderData.userId)
      // This query needs to be robust if 'active' status can be an object.
      // E.g., .where("status.orderStatus", "in", ["active", "confirmed", "preparing"])
      .where("status", "==", "active"); // Simple check for string "active"
    
    const activeOrderSnapshot = await activeOrderQuery.get();
    if (!activeOrderSnapshot.empty) {
      // Check if the found active order is different from the one potentially being retried/updated
      let isDifferentActiveOrder = true;
      if (orderData.orderId) {
        activeOrderSnapshot.forEach((doc: DocumentData) => { // Added type for doc
          if (doc.id === orderData.orderId) {
            isDifferentActiveOrder = false; // It's the same order, perhaps a retry, allow update.
          }
        });
      }
      if (isDifferentActiveOrder) {
         console.warn(`[Admin Service] User ${orderData.userId} already has an active order. Blocking creation of new order ${orderData.orderId}.`);
         throw new Error(`User ${orderData.userId} already has an active order. Please complete or cancel it before placing a new one.`);
      }
    }

    const dataToSet: any = {
      orderId: orderData.orderId,
      items: orderData.items.map(item => {
        const details: any = { // Build details object carefully
          id: item.details.id,
          name: item.details.name,
          price: item.details.price,
          quantity: item.details.quantity,
        };
        if (item.details.image !== undefined) details.image = item.details.image;
        if (item.details.aguaDelDia !== undefined) details.aguaDelDia = item.details.aguaDelDia;
        if (item.details.entrada !== undefined) details.entrada = item.details.entrada;
        if (item.details.platoFuerte !== undefined) details.platoFuerte = item.details.platoFuerte;
        if (item.details.sopa !== undefined) details.sopa = item.details.sopa;
        return { details };
      }),
      deliveryInfo: orderData.deliveryInfo,
      deliveryDateTime: finalDeliveryDateTime,
      paymentMethod: orderData.paymentMethod,
      totalAmount: orderData.totalAmount,
      userId: orderData.userId,
      restaurantId: orderData.restaurantId,
      status: orderData.initialStatus || "active", // Default to "active" if no initialStatus
      timestamp: FieldValue.serverTimestamp(), // Admin SDK server timestamp
    };

    if (orderData.paymentDetails) {
      dataToSet.paymentDetails = orderData.paymentDetails;
    }

    // Use a batch for atomic writes of order and user update
    const batch = adminDb.batch();
    batch.set(orderRef, dataToSet);
    batch.update(userRef, { latestOrderId: orderData.orderId });
    
    await batch.commit();
    console.log(`[Admin Service] Order ${orderData.orderId} created in Firestore and user ${orderData.userId} updated successfully.`);

    // Initialize real-time data in Realtime Database using Admin SDK
    try {
      const rtdbOrderRef = adminRtdb.ref(`triada-culinaria-orders/${orderData.orderId}`);
      const initialRTDBData = {
        status: {
          orderStatus: "confirmed", // Or derive from orderData.initialStatus if it's an object
          progress: 25,
          estimatedTime: 45
        },
        tracking: {
          deliveryPersonId: null,
          locationUpdates: []
        },
        notifications: {
          initial: {
            message: "Tu pedido ha sido recibido y confirmado",
            timestamp: Date.now(), // Consider FieldValue.serverTimestamp() if RTDB supports it via admin
            read: false
          }
        },
        customerInteraction: {
          customerFeedback: null,
          rating: null
        }
      };
      await rtdbOrderRef.set(initialRTDBData);

      const restaurantOrderRef = adminRtdb.ref(`restaurants/${orderData.restaurantId}/active-triada-culinaria-orders/${orderData.orderId}`);
      await restaurantOrderRef.set(true);
      console.log(`[Admin Service] Order ${orderData.orderId} initialized in Realtime Database.`);

    } catch (rtdbError) {
      console.error(`[Admin Service] Failed to initialize order ${orderData.orderId} in Realtime Database:`, rtdbError);
      // Decide if this error should cause the whole operation to fail or just be logged.
      // For now, logging and continuing, but this might leave data inconsistent.
    }
    
    return orderData.orderId;

  } catch (error: any) {
    console.error(`[Admin Service] Error in createOrderAndInitializeRTDBAsAdmin (Firestore part) for orderId ${orderData.orderId}:`, JSON.stringify(error, null, 2));
    // Log the full error object if it has more details
    if (error.errorInfo) {
      console.error("[Admin Service] Firebase Error Info:", JSON.stringify(error.errorInfo, null, 2));
    }
    throw error; // Re-throw to be caught by the calling service/API route
  }
};

export const initializeRealTimeOrder = async (orderId: string, restaurantId: string): Promise<void> => {
  console.log(`[Admin Service] Initializing real-time order for orderId: ${orderId}, restaurantId: ${restaurantId}`);
  if (!admin.app().options.databaseURL) {
    console.error('[Admin Service] initializeRealTimeOrder: Default Firebase Admin App is missing databaseURL.');
    throw new Error("Firebase Admin App not properly initialized with databaseURL for RTDB operations.");
  }
  const adminRtdb = admin.database();

  try {
    const rtdbOrderRef = adminRtdb.ref(`triada-culinaria-orders/${orderId}`);
    const initialRTDBData = {
      status: {
        orderStatus: "confirmed",
        progress: 25,
        estimatedTime: 45
      },
      tracking: {
        deliveryPersonId: null,
        locationUpdates: []
      },
      notifications: {
        initial: {
          message: "Tu pedido ha sido recibido y confirmado.",
          timestamp: Date.now(),
          read: false
        }
      },
      customerInteraction: {
        customerFeedback: null,
        rating: null
      }
    };
    await rtdbOrderRef.set(initialRTDBData);

    // Also ensure the order is marked in the restaurant's active orders list if that's part of initialization
    const restaurantOrderRef = adminRtdb.ref(`restaurants/${restaurantId}/active-triada-culinaria-orders/${orderId}`);
    await restaurantOrderRef.set(true); // Mark as active

    console.log(`[Admin Service] Order ${orderId} (re)initialized in Realtime Database for restaurant ${restaurantId}.`);
  } catch (rtdbError) {
    console.error(`[Admin Service] Failed to initialize order ${orderId} in Realtime Database during standalone initialization:`, JSON.stringify(rtdbError, null, 2));
    throw rtdbError; // Re-throw to be handled by the caller
  }
};

/**
 * Retrieves a user profile by ID using the Admin SDK (bypasses security rules).
 * @param userId The ID of the user to retrieve.
 * @returns The user profile data or null if not found.
 */
export const getUserProfileAsAdmin = async (userId: string): Promise<UserProfileAdmin | null> => {
  console.log(`[Admin Service] Getting user profile for userId: ${userId}`);
  if (!userId) {
    console.error("[Admin Service] getUserProfileAsAdmin: userId is required.");
    return null;
  }
  try {
    const userRef = adminDb.collection('users').doc(userId);
    const userSnap = await userRef.get();

    if (userSnap.exists) {
      // Combine document ID with its data
      return { id: userSnap.id, ...userSnap.data() } as UserProfileAdmin;
    } else {
      console.warn(`[Admin Service] No user found with ID: ${userId} when fetching as admin.`);
      return null;
    }
  } catch (error) {
    console.error(`[Admin Service] Error getting user profile for ID ${userId} as admin:`, JSON.stringify(error, null, 2));
    // Depending on policy, you might want to throw, or return null to indicate failure
    // For now, re-throwing to make it visible if there's an unexpected issue with Admin SDK itself
    throw error;
  }
};

/**
 * Creates a new user profile in Firestore with the given UID and data.
 * @param uid The UID of the user.
 * @param userData The data for the new user.
 * @returns The created user profile data.
 */
export const createUserWithUid = async (uid: string, userData: Omit<UserProfileAdmin, 'id'>): Promise<UserProfileAdmin> => {
  console.log(`[Admin Service] Creating user with UID: ${uid} and data:`, JSON.stringify(userData, null, 2));
  if (!uid || !userData) {
    throw new Error("[Admin Service] createUserWithUid: UID and userData are required.");
  }
  try {
    const userRef = adminDb.collection('users').doc(uid);
    // Ensure server timestamp for createdAt if not already a Timestamp
    const dataToSet = {
      ...userData,
      createdAt: userData.createdAt instanceof Date ? Timestamp.fromDate(userData.createdAt) : userData.createdAt || FieldValue.serverTimestamp(),
      lastLoginAt: userData.lastLoginAt instanceof Date ? Timestamp.fromDate(userData.lastLoginAt) : userData.lastLoginAt || FieldValue.serverTimestamp(),
    };
    await userRef.set(dataToSet);
    console.log(`[Admin Service] User profile created successfully for UID: ${uid}`);
    return { id: uid, ...userData } as UserProfileAdmin; // Return the input data structured as UserProfileAdmin
  } catch (error) {
    console.error(`[Admin Service] Error creating user profile for UID ${uid}:`, JSON.stringify(error, null, 2));
    throw error;
  }
};

/**
 * Updates the last login timestamp for a user.
 * @param uid The UID of the user to update.
 */
export const updateUserLastLogin = async (uid: string): Promise<void> => {
  console.log(`[Admin Service] Updating last login for user UID: ${uid}`);
  if (!uid) {
    throw new Error("[Admin Service] updateUserLastLogin: UID is required.");
  }
  try {
    const userRef = adminDb.collection('users').doc(uid);
    await userRef.update({ lastLoginAt: FieldValue.serverTimestamp() }); // Use server timestamp for accuracy
    console.log(`[Admin Service] Updated lastLoginAt for user UID: ${uid}`);
  } catch (error) {
    console.error(`[Admin Service] Error updating lastLoginAt for user UID ${uid}:`, JSON.stringify(error, null, 2));
    // Decide if this should throw or just log. For now, re-throwing.
    throw error;
  }
};
